version: "3.7"

services:
  spark-master:
    container_name: spark-master
    hostname: spark-master
    image: magiplatform/spark:latest
    entrypoint: /opt/app/bin/master.sh
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_CLUSTER_DEBUG: "true"
    ports:
      - "7077:7077"
      - "8080:8080"
      - "6066:6066"
      - "5050:5050"
    networks:
      - spark

  spark-worker-1:
    container_name: spark-worker-1
    hostname: spark-worker-1
    image: magiplatform/spark:latest
    entrypoint: /opt/app/bin/worker.sh
    environment:
      SPARK_MASTER_HOST: spark-master
    ports:
      - "7078:7078"
      - "8081:8081"
      - "5051:5050"
    depends_on:
      - spark-master
    networks:
      - spark

  spark-worker-2:
    container_name: spark-worker-2
    hostname: spark-worker-2
    image: magiplatform/spark:latest
    entrypoint: /opt/app/bin/worker.sh
    environment:
      SPARK_MASTER_HOST: spark-master
    ports:
      - "7079:7078"
      - "8082:8081"
      - "5052:5050"
    depends_on:
      - spark-master
    networks:
      - spark


networks:
  spark:
